language: node_js
node_js:
  - "6.10.0"
sudo: required
notifications:
  email:
    - false
cache:
  directories:
    - node_modules
addons: 
  apt:
    packages:
      - xvfb
install: 
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
script:
  - "webpack && npm test"